name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
      ECR_REGISTRY_URL: 405266377051.dkr.ecr.us-east-2.amazonaws.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL/project
      
      - name: Build Docker image
        run: docker build -t project .

      - name: Tag Docker image
        run: docker tag project $ECR_REGISTRY_URL/project:0.0.2

      - name: Push Docker image to ECR
        run: docker push $ECR_REGISTRY_URL/project:0.0.2