name: Dockerfile Linter

on:
  workflow_dispatch:
   pull_requests: 
    bramches: [main]

jobs:
  lint_dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request' && failure()
        with:
         script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })